import { motion } from "framer-motion";
import { Activity, Target, Bot } from "lucide-react";
import Section, { Container, SectionLabel } from "@/components/ui/Section";

const FEATURES = [
  {
    icon: Activity,
    title: "Financial Health Analysis",
    description:
      "Get a comprehensive score of your financial wellbeing. FinPilot AI evaluates your income, expenses, savings rate, debt-to-income ratio, and emergency fund coverage to produce an actionable health report.",
    accent: "#0F62FE",
  },
  {
    icon: Target,
    title: "Budget & Savings Planning",
    description:
      "Define your financial goals and let AI construct a realistic plan. Identify wasteful spending patterns, optimize your budget allocation, and set savings milestones with automated progress tracking.",
    accent: "#0F62FE",
  },
  {
    icon: Bot,
    title: "Powered by IBM Watson Orchestrate",
    description:
      "Every recommendation is generated by an enterprise-grade AI agent built on IBM Watson Orchestrate — providing reliable, context-aware financial coaching you can continue in a natural conversation.",
    accent: "#0F62FE",
  },
];

const cardVariants = {
  hidden:  { opacity: 0, y: 32 },
  show:    { opacity: 1, y: 0   },
};

export default function Features() {
  return (
    <Section id="features">
      <Container>
        {/* ── Header ─────────────────────────────────────── */}
        <div className="text-center max-w-2xl mx-auto mb-16">
          <SectionLabel>Core Capabilities</SectionLabel>
          <h2 className="text-3xl sm:text-4xl font-bold text-white tracking-tight mb-4">
            Everything you need to take control of your finances
          </h2>
          <p className="text-base text-text-secondary leading-relaxed">
            Three powerful tools working together to give you a complete picture
            of your financial health and a clear path forward.
          </p>
        </div>

        {/* ── Cards ──────────────────────────────────────── */}
        <motion.div
          className="grid grid-cols-1 md:grid-cols-3 gap-5"
          initial="hidden"
          whileInView="show"
          viewport={{ once: true, margin: "-80px" }}
          transition={{ staggerChildren: 0.15 }}
        >
          {FEATURES.map((feature) => (
            <FeatureCard key={feature.title} {...feature} />
          ))}
        </motion.div>
      </Container>
    </Section>
  );
}

function FeatureCard({ icon: Icon, title, description }) {
  return (
    <motion.div
      variants={cardVariants}
      transition={{ duration: 0.5, ease: "easeOut" }}
      whileHover={{ y: -4, transition: { duration: 0.2 } }}
      className="group relative bg-[rgba(255,255,255,0.03)] border border-[rgba(255,255,255,0.08)] hover:border-[rgba(15,98,254,0.35)] rounded-2xl p-7 flex flex-col gap-5 cursor-default transition-colors duration-300"
    >
      {/* Subtle hover glow */}
      <div className="absolute inset-0 rounded-2xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 bg-[radial-gradient(ellipse_at_top_left,rgba(15,98,254,0.06),transparent_70%)] pointer-events-none" />

      {/* Icon */}
      <span className="flex items-center justify-center w-11 h-11 rounded-xl bg-[rgba(15,98,254,0.12)] border border-[rgba(15,98,254,0.20)] group-hover:bg-[rgba(15,98,254,0.20)] transition-colors duration-300">
        <Icon size={20} className="text-ibm-blue-light" strokeWidth={1.7} />
      </span>

      {/* Content */}
      <div>
        <h3 className="text-base font-semibold text-white mb-2">{title}</h3>
        <p className="text-sm text-text-secondary leading-relaxed">{description}</p>
      </div>
    </motion.div>
  );
}
